server:
  port: 8000

spring:
  application:
    name: ziye_app_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.aiziye.cn:3306/ziye_app?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ziye1011

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    host: localhost
    port: 63791

  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2296543112@qq.com
    password: nygwtysgtfllebad
    test-connection: false
    default-encoding: utf-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

file:
  upload:
    dir: "/upload"

